<?php
return array(
	'id' => 'content_id',
	'name' => 'content.title',
	'cat' => 'content.cat_id',
	'avatar' => 'content.thumb_id',
	'created' => 'content.created',
	'modified' => 'content.modified',
	'status' => 'content.status',
	'nick' => 'content_crm.nick',
	'email' => 'content_crm.email',
	'rela' => 'content_crm.rela',
	'affinities' => 'content_crm.affinities',
	'gender' => 'content_crm.gender',
	'birthday' => 'content_crm.birthday',
	'degree' => 'content_crm.degree',
	'skill' => 'content_crm.skill',
	'habit' => 'content_crm.habit',
	'interest' => 'content_crm.interest',
	'conduct' => 'content_crm.conduct',
	'city' => 'content_crm.city',
	'address' => 'content_crm.address',
	'phone' => 'content_crm.phone',
	'mantra' => 'content_crm.mantra',
	'company' => 'content_crm.company',
	'job' => 'content_crm.job',
	'appointment_time' => 'content_crm.appointment_time',
	'appointment_event' => 'content_crm.appointment_event',
	'history' => 'content_crm.history',
	'entrust' => 'content_crm.entrust',
	'entrust_me' => 'content_crm.entrust_me',
	'attach_ids' => 'content_crm.attach_ids',
	'family' => 'content_crm.family',
);